/*
Copyright (c) 2014-2023 VMware, Inc. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"os"

	_ "github.com/zhengkes/govmomi/govc/about"
	"github.com/zhengkes/govmomi/govc/cli"
	_ "github.com/zhengkes/govmomi/govc/cluster"
	_ "github.com/zhengkes/govmomi/govc/cluster/draft"
	_ "github.com/zhengkes/govmomi/govc/cluster/draft/baseimage"
	_ "github.com/zhengkes/govmomi/govc/cluster/draft/component"
	_ "github.com/zhengkes/govmomi/govc/cluster/group"
	_ "github.com/zhengkes/govmomi/govc/cluster/module"
	_ "github.com/zhengkes/govmomi/govc/cluster/override"
	_ "github.com/zhengkes/govmomi/govc/cluster/rule"
	_ "github.com/zhengkes/govmomi/govc/cluster/vlcm"
	_ "github.com/zhengkes/govmomi/govc/datacenter"
	_ "github.com/zhengkes/govmomi/govc/datastore"
	_ "github.com/zhengkes/govmomi/govc/datastore/cluster"
	_ "github.com/zhengkes/govmomi/govc/datastore/disk"
	_ "github.com/zhengkes/govmomi/govc/datastore/maintenance"
	_ "github.com/zhengkes/govmomi/govc/datastore/vsan"
	_ "github.com/zhengkes/govmomi/govc/device"
	_ "github.com/zhengkes/govmomi/govc/device/cdrom"
	_ "github.com/zhengkes/govmomi/govc/device/clock"
	_ "github.com/zhengkes/govmomi/govc/device/floppy"
	_ "github.com/zhengkes/govmomi/govc/device/model"
	_ "github.com/zhengkes/govmomi/govc/device/pci"
	_ "github.com/zhengkes/govmomi/govc/device/scsi"
	_ "github.com/zhengkes/govmomi/govc/device/serial"
	_ "github.com/zhengkes/govmomi/govc/device/usb"
	_ "github.com/zhengkes/govmomi/govc/disk"
	_ "github.com/zhengkes/govmomi/govc/disk/snapshot"
	_ "github.com/zhengkes/govmomi/govc/dvs"
	_ "github.com/zhengkes/govmomi/govc/dvs/portgroup"
	_ "github.com/zhengkes/govmomi/govc/env"
	_ "github.com/zhengkes/govmomi/govc/events"
	_ "github.com/zhengkes/govmomi/govc/export"
	_ "github.com/zhengkes/govmomi/govc/extension"
	_ "github.com/zhengkes/govmomi/govc/fields"
	_ "github.com/zhengkes/govmomi/govc/folder"
	_ "github.com/zhengkes/govmomi/govc/host"
	_ "github.com/zhengkes/govmomi/govc/host/account"
	_ "github.com/zhengkes/govmomi/govc/host/autostart"
	_ "github.com/zhengkes/govmomi/govc/host/cert"
	_ "github.com/zhengkes/govmomi/govc/host/date"
	_ "github.com/zhengkes/govmomi/govc/host/esxcli"
	_ "github.com/zhengkes/govmomi/govc/host/firewall"
	_ "github.com/zhengkes/govmomi/govc/host/maintenance"
	_ "github.com/zhengkes/govmomi/govc/host/option"
	_ "github.com/zhengkes/govmomi/govc/host/portgroup"
	_ "github.com/zhengkes/govmomi/govc/host/service"
	_ "github.com/zhengkes/govmomi/govc/host/storage"
	_ "github.com/zhengkes/govmomi/govc/host/vnic"
	_ "github.com/zhengkes/govmomi/govc/host/vswitch"
	_ "github.com/zhengkes/govmomi/govc/importx"
	_ "github.com/zhengkes/govmomi/govc/library"
	_ "github.com/zhengkes/govmomi/govc/library/policy"
	_ "github.com/zhengkes/govmomi/govc/library/session"
	_ "github.com/zhengkes/govmomi/govc/library/subscriber"
	_ "github.com/zhengkes/govmomi/govc/library/trust"
	_ "github.com/zhengkes/govmomi/govc/license"
	_ "github.com/zhengkes/govmomi/govc/logs"
	_ "github.com/zhengkes/govmomi/govc/ls"
	_ "github.com/zhengkes/govmomi/govc/metric"
	_ "github.com/zhengkes/govmomi/govc/metric/interval"
	_ "github.com/zhengkes/govmomi/govc/namespace"
	_ "github.com/zhengkes/govmomi/govc/namespace/cluster"
	_ "github.com/zhengkes/govmomi/govc/namespace/service"
	_ "github.com/zhengkes/govmomi/govc/namespace/vmclass"
	_ "github.com/zhengkes/govmomi/govc/object"
	_ "github.com/zhengkes/govmomi/govc/option"
	_ "github.com/zhengkes/govmomi/govc/permissions"
	_ "github.com/zhengkes/govmomi/govc/pool"
	_ "github.com/zhengkes/govmomi/govc/role"
	_ "github.com/zhengkes/govmomi/govc/session"
	_ "github.com/zhengkes/govmomi/govc/sso/group"
	_ "github.com/zhengkes/govmomi/govc/sso/idp"
	_ "github.com/zhengkes/govmomi/govc/sso/lpp"
	_ "github.com/zhengkes/govmomi/govc/sso/service"
	_ "github.com/zhengkes/govmomi/govc/sso/user"
	_ "github.com/zhengkes/govmomi/govc/storage/policy"
	_ "github.com/zhengkes/govmomi/govc/tags"
	_ "github.com/zhengkes/govmomi/govc/tags/association"
	_ "github.com/zhengkes/govmomi/govc/tags/category"
	_ "github.com/zhengkes/govmomi/govc/task"
	_ "github.com/zhengkes/govmomi/govc/vapp"
	_ "github.com/zhengkes/govmomi/govc/vcsa/access/consolecli"
	_ "github.com/zhengkes/govmomi/govc/vcsa/access/dcui"
	_ "github.com/zhengkes/govmomi/govc/vcsa/access/shell"
	_ "github.com/zhengkes/govmomi/govc/vcsa/access/ssh"
	_ "github.com/zhengkes/govmomi/govc/vcsa/log"
	_ "github.com/zhengkes/govmomi/govc/vcsa/proxy"
	_ "github.com/zhengkes/govmomi/govc/vcsa/shutdown"
	_ "github.com/zhengkes/govmomi/govc/version"
	_ "github.com/zhengkes/govmomi/govc/vlcm/depot/content/baseimages"
	_ "github.com/zhengkes/govmomi/govc/vlcm/depot/offline"
	_ "github.com/zhengkes/govmomi/govc/vm"
	_ "github.com/zhengkes/govmomi/govc/vm/dataset"
	_ "github.com/zhengkes/govmomi/govc/vm/dataset/entry"
	_ "github.com/zhengkes/govmomi/govc/vm/disk"
	_ "github.com/zhengkes/govmomi/govc/vm/guest"
	_ "github.com/zhengkes/govmomi/govc/vm/network"
	_ "github.com/zhengkes/govmomi/govc/vm/option"
	_ "github.com/zhengkes/govmomi/govc/vm/rdm"
	_ "github.com/zhengkes/govmomi/govc/vm/snapshot"
	_ "github.com/zhengkes/govmomi/govc/vm/target"
	_ "github.com/zhengkes/govmomi/govc/volume"
	_ "github.com/zhengkes/govmomi/govc/volume/snapshot"
	_ "github.com/zhengkes/govmomi/govc/vsan"
)

func main() {
	os.Exit(cli.Run(os.Args[1:]))
}
